# core/execution/failure_recovery.py

"""
Failure Recovery Manager

Purpose:
Deterministic failure handling during execution.

This module:
- DOES NOT execute steps
- DOES NOT touch OS
- DOES NOT read screen directly
- DOES NOT mutate external state

It is a bounded policy engine that decides:
retry | alternative | abort
"""

from dataclasses import dataclass
from typing import Dict, Any, Optional, List
import json

from core.schemas.execution_plan import ExecutionStep


# ==================================================
# RECOVERY ACTION
# ==================================================

@dataclass(frozen=True)
class RecoveryAction:
    """
    Immutable recovery decision.

    action:
      - "retry"
      - "alternative"
      - "abort"
    """
    action: str
    reason: Optional[str] = None
    delay: float = 0.0
    context: Optional[Dict[str, Any]] = None
    alternative_operations: Optional[List[Dict[str, Any]]] = None


# ==================================================
# FAILURE RECOVERY MANAGER
# ==================================================

class FailureRecoveryManager:
    """
    Bounded failure recovery engine.

    HARD CONTRACT:
    - No execution
    - No randomness
    - Deterministic fallback always available
    """

    MAX_RETRIES = 3
    RETRY_DELAY_SECONDS = 2.0

    _VALID_ACTIONS = {"retry", "alternative", "abort"}

    # -------------------------------------------------
    # PRIMARY ENTRYPOINT (Deterministic)
    # -------------------------------------------------

    def handle_failure(
        self,
        step: ExecutionStep,
        error: Exception,
        attempt_ctx: Dict[str, Any],
    ) -> RecoveryAction:

        if not isinstance(step, ExecutionStep):
            raise ValueError("Invalid step for recovery")

        if not isinstance(attempt_ctx, dict):
            attempt_ctx = {}

        attempt = int(attempt_ctx.get("attempt", 0))

        # ---- non-retryable ----
        if not getattr(step, "retryable", True):
            return self._abort(
                reason=f"Step {step.id} marked non-retryable: {error}"
            )

        # ---- bounded retry ----
        if attempt < self.MAX_RETRIES:
            return self._retry(
                attempt=attempt,
                error=error,
            )

        # ---- explicit alternatives ----
        alternatives = self._extract_alternatives(step)
        if alternatives:
            return RecoveryAction(
                action="alternative",
                reason=(
                    f"Retry budget exhausted for step {step.id}, "
                    f"attempting explicit alternatives"
                ),
                alternative_operations=alternatives,
            )

        # ---- fail-closed abort ----
        return self._abort(
            reason=f"Max retries exceeded for step {step.id}: {error}"
        )

    # -------------------------------------------------
    # OPTIONAL PERCEPTION-AWARE PATH
    # -------------------------------------------------

    def handle_failure_with_perception(
        self,
        *,
        step: ExecutionStep,
        error: Exception,
        attempt_ctx: Dict[str, Any],
        world_graph=None,
        llm_callable=None,
    ) -> RecoveryAction:
        """
        Perception-aware recovery.

        If LLM unavailable → falls back to deterministic policy.
        """

        # Always respect deterministic limits first
        deterministic_action = self.handle_failure(step, error, attempt_ctx)

        attempt = int((attempt_ctx or {}).get("attempt", 0))

        # Only attempt reasoning after first failure
        if attempt < 1:
            return deterministic_action

        if not world_graph or not llm_callable:
            return deterministic_action

        try:
            snapshot = world_graph.snapshot()

            prompt = self._build_llm_prompt(
                step=step,
                error=error,
                snapshot=snapshot,
            )

            raw = llm_callable(prompt)
            decision = json.loads(raw.strip())

            action = decision.get("action")

            if action not in self._VALID_ACTIONS:
                return deterministic_action

            if action == "retry":
                return RecoveryAction(
                    action="retry",
                    reason=f"LLM: {decision.get('reason')}",
                    delay=min(
                        float(decision.get("suggested_delay", 2.0)),
                        5.0,
                    ),
                    context={"attempt": attempt + 1},
                )

            if action == "abort":
                return RecoveryAction(
                    action="abort",
                    reason=f"LLM: {decision.get('reason')}",
                )

            # alternatives not auto-generated by LLM
            return deterministic_action

        except Exception:
            # Fail closed to deterministic policy
            return deterministic_action

    # ==================================================
    # INTERNAL HELPERS
    # ==================================================

    def _retry(self, *, attempt: int, error: Exception) -> RecoveryAction:
        return RecoveryAction(
            action="retry",
            reason=f"Retry {attempt + 1}/{self.MAX_RETRIES}: {error}",
            delay=self.RETRY_DELAY_SECONDS,
            context={"attempt": attempt + 1},
        )

    def _abort(self, *, reason: str) -> RecoveryAction:
        return RecoveryAction(
            action="abort",
            reason=reason,
        )

    def _extract_alternatives(
        self,
        step: ExecutionStep,
    ) -> Optional[List[Dict[str, Any]]]:

        action = getattr(step, "action", None)
        if not isinstance(action, dict):
            return None

        alternatives = action.get("alternatives")

        if not isinstance(alternatives, list) or not alternatives:
            return None

        validated: List[Dict[str, Any]] = []
        for alt in alternatives:
            if isinstance(alt, dict):
                validated.append(alt)

        return validated or None

    def _build_llm_prompt(
        self,
        *,
        step: ExecutionStep,
        error: Exception,
        snapshot: Dict[str, Any],
    ) -> str:

        return f"""
You are a bounded recovery policy engine.

FAILED STEP:
- id: {step.id}
- type: {step.type.value}
- description: {step.description}

ERROR:
{str(error)[:300]}

CURRENT WORLD STATE:
- focused_app: {snapshot.get("focused_app")}
- entity_count: {snapshot.get("entity_count")}
- visible_elements_sample:
{json.dumps(snapshot.get("entities", [])[:10], indent=2)}

Decide strictly:

Return JSON only:
{{
  "action": "retry" | "abort",
  "reason": "short explanation",
  "suggested_delay": 0-5
}}

Rules:
- Retry only if screen state suggests temporary failure.
- Abort if impossible in current state.
- Be conservative.
"""
